#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

# http://example.com/blog
# &--m12_plugin_blog-postplugin[@package]=M12.Plugin.Blog&--m12_plugin_blog-postplugin[@controller]=Post&--m12_plugin_blog-postplugin[@action]=index&--m12_plugin_blog-postplugin[--posts-paginator][@package]=&--m12_plugin_blog-postplugin[--posts-paginator][@subpackage]=&--m12_plugin_blog-postplugin[--posts-paginator][@controller]=&--m12_plugin_blog-postplugin[--posts-paginator][@action]=index&--m12_plugin_blog-postplugin[--posts-paginator][currentPage]=2

-
  name: 'Blog post pagination'
  uriPattern:    '{node}/p/{--m12_plugin_blog-postplugin.--posts-paginator.currentPage}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--m12_plugin_blog-postplugin':
      '@package':     'M12.Plugin.Blog'
      '@controller':  'Post'
      '@action':      'index'
      '--posts-paginator':
        '@package': ''
        '@subpackage': ''
        '@controller': ''
        '@action': 'index'
        'currentPage': '1'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: false


-
  name:          'RSS Feed routing'
  uriPattern:    '{node}.rss.xml'
  defaults:
    '@package':    'M12.Plugin.Blog'
    '@controller': 'Rss'
    '@format':     'xml'
    '@action':     'rss'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
