TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Plugin.Blog': TRUE

M12:
  Plugin:
    Blog:
      disqus:
        enabled: FALSE
        shortname: ''
      feed:
        uri: '/blog.rss.xml'
        postsLimit: 20
        title: 'TYPO3 Neos Blog'
        description: 'Blog powered by TYPO3 Neos'
        defaultAuthor: 'Wawel Dragon'
